version: '3'
services:
  commandlinetools:
    container_name: android_build_commandlinetools-29.0.3_6.5
    image: kaihei777/android_build_docker_container:commandlinetools-29.0.3_6.5
    build:
      context: .
      args:
        ANDROID_SDK_TOOLS: "6858069"
        GRADLE_VERSION: "6.5"
        ANDROID_BUILD_TOOLS: "29.0.3"
        USE_NDK: "yes"
