version: '3'
services:
  commandlinetools:
    container_name: android_build_commandlinetools-29.0.3
    image: kaihei777/android_build_docker_container:commandlinetools-29.0.3
    build:
      context: .
      args:
        ANDROID_SDK_TOOLS: "6609375"
        GRADLE_VERSION: "6.1.1"
        ANDROID_BUILD_TOOLS: "29.0.3"
        USE_NDK: "yes"
