version: '3'
services:
  commandlinetools:
    container_name: android_build_commandlinetools
    image: kaihei777/android_build_docker_container:commandlinetools
    build:
      context: .
      args:
        ANDROID_SDK_TOOLS: "6200805"
        GRADLE_VERSION: "5.6.4"
