version: '3'
services:
  commandlinetools:
    container_name: android_build_commandlinetools-29.0.2
    image: kaihei777/android_build_docker_container:commandlinetools-29.0.2
    build:
      context: .
      args:
        ANDROID_SDK_TOOLS: "6514223"
        GRADLE_VERSION: "6.1.1"
        ANDROID_BUILD_TOOLS: "29.0.2"
        USE_NDK: "no"
