version: '3'
services:
  commandlinetools:
    container_name: android_build_commandlinetools-30.0.3_6.7.1
    image: kaihei777/android_build_docker_container:commandlinetools-30.0.3_6.7.1
    build:
      context: .
      args:
        ANDROID_SDK_TOOLS: "7302050"
        GRADLE_VERSION: "6.7.1"
        ANDROID_BUILD_TOOLS: "30.0.3"
        USE_NDK: "yes"
