version: '3'
services:
  commandlinetools:
    container_name: android_build_commandlinetools-28.0.3
    image: kaihei777/android_build_docker_container:commandlinetools-28.0.3
    build:
      context: .
      args:
        ANDROID_SDK_TOOLS: "6200805"
        GRADLE_VERSION: "5.6.4"
        ANDROID_BUILD_TOOLS: "28.0.3"
        USE_NDK: "no"
